version: '3.3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: auction-app
    working_dir: /home/www/html
    environment:
      APP_ENV: local
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 # for xdebug
      PHP_IDE_CONFIG: serverName=docker # for xdebug
    volumes:
      - ./:/home/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # comment out this will disable xdebug
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf # mapping supervisord.conf
    networks:
      - auction-network

  #Database
  db:
    image: mysql:5.7.22
    container_name: auction-db
    ports:
      - 3390:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword
      MYSQL_DATABASE: auction-db
      MYSQL_USER: auction-user
      MYSQL_PASSWORD: mysecurepassword
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - auction-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: auction-webserver
    depends_on:
      - app
    ports:
      - 90:80
      - 490:443
    volumes:
      - ./:/home/www/html
      - ./logs:/var/log/nginx
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - auction-network

#Docker Networks
networks:
  auction-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
